stages:
  - init
  - plan

variables:
  TF_VAR_organization: "nbs007"

init:
  stage: init
  image: "hashicorp/terraform:latest"
  script:
    - export TF_TOKEN="$TF_VAR_token"
    - export TF_WORKSPACE="$TF_VAR_workspace"
    - terraform init \
        -backend-config="address=https://app.terraform.io" \
        -backend-config="organization=$TF_VAR_organization" \
        -backend-config="workspaces.name=$TF_VAR_workspace" \
        -backend-config="token=$TF_VAR_token"

plan:
  stage: plan
  image: "hashicorp/terraform:latest"
  script:
    - terraform plan \
        -var="some_variable=value"
