stages:
 - plan

variables:
 TF_VAR_token: $CI_JOB_TOKEN
 TF_VAR_workspace: $CI_COMMIT_REF_NAME

plan :
 stage: init
 image: ruby:3.1
 script:
    - apt-get update && apt-get install -y unzip # Install unzip (required for Terraform)
    - curl -fsSL https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip -o terraform.zip
    - unzip terraform.zip -d /usr/local/bin
    - export TF_TOKEN=$TF_VAR_token
    - export TF_WORKSPACE=$TF_VAR_workspace
    - terraform login
    - terraform init
    - terraform plan
 only:
    - main
 when: always