name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Update to use Node.js 16
          node-version: '16'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # Update to use Node.js 16
          tf_version: '1.1.0'
          node_version: '16'

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
